name: Run Discord Daily Bot (schedule + manual)

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Announce run
        run: echo "Discord Daily Bot scheduled/manual run at $(date)" > run.txt

      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: run-logs
          path: run.txt
